name: Import

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - run: pip install mercurial
      
      - run: git clone --depth 1 --branch v221024 https://github.com/frej/fast-export.git

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -lah
          ls -lah *
          fast-export/hg-fast-export.sh -r http://hg.code.sf.net/p/passwdsafe/code
